### ISSUE TITLE
The results of calling `selfdestruct` function in EvernodeSE and Devnet differ. 

### ISSUE THREAD

**Issue by Artem-Zhdanov** [tonlabs/evernode-se#101]
# Problem

We need to destruct the contact and transfer its tokens to some destination account.

## Version
 tonlabs/local-node:0.35.0

## Expected behaviour

-   Desctructed contract has zero balance and "non exists" type.
-   Account destination has positive balance

## Resulting behaviour

-   in Devnet
    -   as expected
-   in Evernode SE
    -   Desctructed contract is not destructed, its balance unchanged, but transfer to destination account exists!
    -   Account destination has positive balance!

## How to reproduce a bug
To reproduce this bug clone https://github.com/Artem-Zhdanov/evernode-se-selfdestruct-bug
```
everdev se start
```
Intall dependencies and run
```
npm i
node selfdestruct.js
```
Open http://localhost and finds accounts in the output

**Comment by elasticLove1** [comment]
Will be fixed in the next releases

**Comment by AlexeyVavilin** [comment]
Fixed in 0.36.0
