### ISSUE TITLE
Broken GiverV2.sol & GiverV3.sol

### ISSUE THREAD

**Issue by FairyFromAlfeya** [tonlabs/evernode-se#103]
### Issue lines:

https://github.com/tonlabs/evernode-se/blob/master/contracts/giver_v2/GiverV2.sol#L57
https://github.com/tonlabs/evernode-se/blob/master/contracts/giver_v3/GiverV3.sol#L58

### Description:

Giver contract passes compilation, but any `sendTransaction` call will be reverted with code 9 (Cell underflow) on mainnet

### Proposal:

Replace all `expireAt` entries with `uint32` instead of `uint64`
[GiverV3.sol.zip](https://github.com/tonlabs/evernode-se/files/10076050/GiverV3.sol.zip)

**Comment by elasticLove1** [comment]
Thank you for the report@FairyFromAlfeya:)  What compiler version do you use?

**Comment by FairyFromAlfeya** [comment]
> Thank you for the report @FairyFromAlfeya :) What compiler version do you use?

0.61.2

**Comment by elasticLove1** [comment]
In the next (0.37.0) Evernode-SE release we decided to update and re-compile GiverV3 version with these changes.
And will make a suggestion not to recompile GiverV2, because it works on old Solidity version.
