### ISSUE TITLE
Contract deletion after flag: 128 + 32 takes too long time

### ISSUE THREAD

**Issue by FairyFromAlfeya** [tonlabs/evernode-se#104]
It takes 160+ seconds when using [locklift](https://github.com/broxus/locklift) for testing. Also removed contract is not accessible from explorer

### Previous behavior:

Takes 2-3 seconds and accessible from explorer

**Comment by elasticLove1** [comment]
Very interesting!  Can you please provide some simple contract blank with this flag and deletion function. Thank you in advance ❤️  @FairyFromAlfeya

**Comment by FairyFromAlfeya** [comment]
Can not provide an example of protocol until open source release. But we have a contract that deploys through the platform and calls other contracts. On the last call, it destroys

I think it's an issue with gql server indexing because some queries take 40 seconds

<img width="724" alt="Screenshot 2022-11-25 at 16 18 08" src="https://user-images.githubusercontent.com/44115243/204014467-14d8ff15-eba0-4afa-8b9c-f487dd7cf008.png">


<img width="1360" alt="Screenshot 2022-11-25 at 16 21 04" src="https://user-images.githubusercontent.com/44115243/204014955-259c163c-90ef-49d5-8817-f13a7d650d92.png">

**Comment by elasticLove1** [comment]
Thank you @FairyFromAlfeya , will look into it

**Comment by AlexeyVavilin** [comment]
@FairyFromAlfeya Please try your test at this image `mnogoborec/evernode-se`. You can run it with 
`docker run -d --name evernode-se -e USER_AGREEMENT=yes -p80:80 "mnogoborec/evernode-se"`
Are there any changes in its behaviour?

**Comment by FairyFromAlfeya** [comment]
> @FairyFromAlfeya Please try your test at this image `mnogoborec/evernode-se`. You can run it with `docker run -d --name evernode-se -e USER_AGREEMENT=yes -p80:80 "mnogoborec/evernode-se"` Are there any changes in its behaviour?

Same behavior:

<img width="722" alt="Screenshot 2022-12-07 at 20 29 09" src="https://user-images.githubusercontent.com/44115243/206277318-b3221dcf-fdc4-4f5d-a84c-dd78905f6c85.png">

<img width="1578" alt="Screenshot 2022-12-07 at 20 30 36" src="https://user-images.githubusercontent.com/44115243/206277646-df4716d4-e08f-4c4b-8528-e11945814163.png">

**Comment by FairyFromAlfeya** [comment]
@elasticLove1 @AlexeyVavilin [Example](https://github.com/FairyFromAlfeya/ever-contract-destroy)

**Comment by AlexeyVavilin** [comment]
@FairyFromAlfeya your example is inaccessible. Did you deleted it?

**Comment by FairyFromAlfeya** [comment]
@AlexeyVavilin Made it private for some time. Should be visible now

**Comment by AlexeyVavilin** [comment]
FIxed in 0.36.0
